---
title: "My english activity log"
---


```{r, echo= FALSE}
#From now on, you will use this article to include every single activity that you do in English in a chronological order (e.g. reading a book in English, watching TV shows and series in English, going to an English Evening in Mons, travelling to an English-speaking country, playing games in English such as the pretty exciting game LyricsTraining, etc.). You can even write a few lines about what you’ve watched/read/done and recommend certain things to your friends. The sky’s the limit! We value personal initiative and we will be happy to read whatever you have to offer.
```
10th october 2019 = I watched few episodes of an american sitcom in english.

3rd november 2019 = I really like stand-up shows, espacially with american humorist, so I watched Daniel Sloss's live shows and Iliza Shlesinger's show on Netflix and it was pretty fun. I recommand it ! 

15th november 2019 = I watched english videos on youtube that were talking about gym exercices. 

18th november 2019 = I watched "Inside Bill's brain " on netflix ( in english ). It's a documentary which talk about Bill Gate's life. 

6th december 2019 = My boyfriend is a great lover of movies, so today we watched " Citizen Kane " together, in english obviously.

During the holidays, I watched a lot of movies in english like Interstellar or Mystic River. 

3th february 2020 = I met one of my new housemate, he comes from Dominican Republic and we can only speak in english. It's a good thing because I can practice my english with him. 
